# Generated by Django 3.2.11 on 2022-01-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('locX', models.CharField(max_length=5)),
                ('locY', models.PositiveIntegerField()),
            ],
        ),
    ]
