# Generated by Django 3.2.11 on 2022-01-17 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_remove_user_email'),
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=2000, null=True)),
                ('seatX', models.CharField(max_length=5, null=True)),
                ('seatY', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('rate', models.FloatField()),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.theater')),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
