# Generated by Django 3.2.11 on 2022-01-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
